name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/Checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/project:v1 .
      
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/project:v1